import { frame, srcOf } from "@/lib/media"
import type { CategorySlug, CollectionSlug, Product } from "@/lib/types"

const apparelSizes = ["S", "M", "L", "XL"]

export const categories: { slug: CategorySlug; name: string; image: string; position?: string; text: string }[] = [
  {
    slug: "chemises",
    name: "Chemises",
    image: srcOf("category-chemises"),
    position: frame("category-chemises").position,
    text: "Col net, coton dense, ligne ouverte.",
  },
  {
    slug: "polos",
    name: "Polos",
    image: srcOf("category-polos"),
    text: "Le col maison, sans ornement inutile.",
  },
  {
    slug: "complets",
    name: "Complets",
    image: srcOf("category-complets"),
    position: frame("category-complets").position,
    text: "Une allure entière, jamais rigide.",
  },
  {
    slug: "t-shirts",
    name: "T-shirts",
    image: srcOf("category-tshirts"),
    position: frame("category-tshirts").position,
    text: "Le jersey qui porte le nom.",
  },
  {
    slug: "pantalons",
    name: "Pantalons",
    image: srcOf("category-pantalons"),
    position: frame("category-pantalons").position,
    text: "La tombée claire, le noir droit.",
  },
  {
    slug: "accessoires",
    name: "Accessoires",
    image: srcOf("category-accessoires"),
    text: "Ce qui termine la tenue.",
  },
]

export const collections: { slug: CollectionSlug; name: string; text: string; image: string; position?: string }[] = [
  {
    slug: "nouvelle-saison",
    name: "Nouvelle saison",
    text: "Les pièces qui ouvrent la garde-robe : lumière, lin d'esprit, lignes plus souples.",
    image: srcOf("campaign-sable"),
    position: frame("campaign-sable").position,
  },
  {
    slug: "essentiels",
    name: "Les essentiels",
    text: "Ce que l'on reprend. Le coton juste, la chemise blanche, le pantalon qui tient.",
    image: srcOf("campaign-chemise"),
    position: frame("campaign-chemise").position,
  },
  {
    slug: "signature",
    name: "Signature",
    text: "Le wordmark, le complet, la couleur bordeaux de la griffe.",
    image: srcOf("hero-campagne"),
    position: frame("hero-campagne").position,
  },
]

export const looks = [
  {
    id: "moluki",
    title: "Moluki",
    text: "Ivoire, bois chaud, le nom posé en deux lignes. La maison se lit d'abord sur le vêtement.",
    image: srcOf("look-moluki"),
    position: frame("look-moluki").position,
    href: "/shop/tee-shirt-griffe",
  },
  {
    id: "alembakate",
    title: "Alembakate",
    text: "Une couche claire, un pantalon qui bouge. L'allure reste ample, la couleur reste chaude.",
    image: srcOf("look-alembakate"),
    position: frame("look-alembakate").position,
    href: "/shop/pantalon-ivoire",
  },
  {
    id: "signature",
    title: "Signature",
    text: "Le noir du complet, relevé par le bordeaux. La teinte du wordmark, tenue autrement.",
    image: srcOf("look-signature"),
    position: frame("look-signature").position,
    href: "/shop/complet-marine",
  },
]

export const seedProducts: Product[] = [
  {
    id: "tee-griffe",
    name: "Tee-shirt Griffe",
    slug: "tee-shirt-griffe",
    description:
      "Jersey ivoire, tombé droit, signé du wordmark bordeaux. La pièce qui porte le nom de la maison, tel qu'il est porté.",
    details:
      "Coton peigné, col rond renforcé, impression ton sur ton bordeaux. Le nom se lit en deux lignes, comme sur la griffe d'origine. Lavage doux, séchage à plat.",
    price: 78,
    category: "t-shirts",
    collection: "signature",
    images: [
      frame("product-tee-griffe"),
      frame("product-tee-coton"),
    ],
    sizes: apparelSizes,
    colors: [{ name: "Ivoire", hex: "#f4efe4" }],
    stock: 18,
    featured: true,
    isNew: true,
    bestseller: true,
    createdAt: "2026-09-01",
  },
  {
    id: "tee-coton",
    name: "Tee-shirt Coton",
    slug: "tee-shirt-coton",
    description: "Le col rond sans inscription. Une base nette, assez lourde pour garder sa forme.",
    details: "Jersey de coton, épaule tombée courte, ourlet droit. Pièce de fond, à porter seule ou sous une chemise ouverte.",
    price: 62,
    category: "t-shirts",
    collection: "essentiels",
    images: [
      frame("product-tee-coton"),
      frame("product-tee-griffe"),
    ],
    sizes: apparelSizes,
    colors: [{ name: "Blanc", hex: "#f7f7f5" }],
    stock: 24,
    featured: false,
    isNew: false,
    bestseller: false,
    createdAt: "2026-06-12",
  },
  {
    id: "chemise-atelier",
    name: "Chemise Atelier",
    slug: "chemise-atelier",
    description: "Col souple, coton dense, épaule nette. Une chemise pensée pour rester ouverte ou fermée.",
    details: "Popeline blanche, boutons nacre, poignet simple. Coupe contemporaine, ni cintrée à l'excès ni oversized.",
    price: 148,
    category: "chemises",
    collection: "essentiels",
    images: [
      frame("product-chemise-atelier"),
      frame("product-chemise-atelier-2"),
    ],
    sizes: apparelSizes,
    colors: [{ name: "Blanc", hex: "#f5f4f1" }],
    stock: 14,
    featured: true,
    isNew: true,
    bestseller: false,
    createdAt: "2026-08-20",
  },
  {
    id: "chemise-nuit",
    name: "Chemise Nuit",
    slug: "chemise-nuit",
    description: "La chemise noire, mate, pour le soir ou pour casser un complet trop sage.",
    details: "Tissu satiné discret, col boutonné, tombée fluide. Se porte rentrée ou sur le pantalon.",
    price: 156,
    category: "chemises",
    collection: "nouvelle-saison",
    images: [
      frame("product-chemise-nuit"),
      frame("product-chemise-nuit-2"),
    ],
    sizes: apparelSizes,
    colors: [{ name: "Noir", hex: "#161514" }],
    stock: 11,
    featured: false,
    isNew: true,
    bestseller: false,
    createdAt: "2026-08-28",
  },
  {
    id: "polo-ivoire",
    name: "Polo Ivoire",
    slug: "polo-ivoire",
    description: "Un polo calme, col tenu, couleur de la toile ivoire. Rien qui crie, tout qui reste.",
    details: "Piqué de coton, col tenu, patte de boutons, manches courtes ourlées.",
    price: 118,
    category: "polos",
    collection: "nouvelle-saison",
    images: [
      frame("product-polo-ivoire"),
    ],
    sizes: apparelSizes,
    colors: [{ name: "Ivoire", hex: "#f3eee6" }],
    stock: 16,
    featured: false,
    isNew: true,
    bestseller: true,
    createdAt: "2026-09-08",
  },
  {
    id: "polo-noir",
    name: "Polo Noir",
    slug: "polo-noir",
    description: "Le même col, passé au noir. Pour le soir léger et les journées trop chaudes pour une chemise.",
    details: "Piqué profond, col qui ne s'affaisse pas. Photo de campagne à remplacer dans l'atelier.",
    price: 118,
    category: "polos",
    collection: "essentiels",
    images: [
      frame("product-polo-noir"),
      frame("campaign-marche"),
    ],
    sizes: apparelSizes,
    colors: [{ name: "Noir", hex: "#141311" }],
    stock: 13,
    featured: true,
    isNew: false,
    bestseller: true,
    createdAt: "2026-05-02",
  },
  {
    id: "pantalon-ivoire",
    name: "Pantalon Ivoire",
    slug: "pantalon-ivoire",
    description: "Le pantalon clair porté avec la griffe. Souple, droit, assez habillé pour ne pas être un jogging.",
    details: "Tissu sec à la main, pince discrète, taille mi-haute. La photo de référence montre la tombée réelle, sur le modèle de la maison.",
    price: 168,
    category: "pantalons",
    collection: "signature",
    images: [
      frame("product-pantalon-ivoire"),
      frame("product-pantalon-ivoire-2"),
    ],
    sizes: apparelSizes,
    colors: [{ name: "Ivoire", hex: "#efe6d6" }],
    stock: 10,
    featured: true,
    isNew: false,
    bestseller: true,
    createdAt: "2026-04-18",
  },
  {
    id: "pantalon-noir",
    name: "Pantalon Noir",
    slug: "pantalon-noir",
    description: "Coupe droite, noir mat. Le bas du complet, ou un pantalon seul sous une chemise blanche.",
    details: "Laine froide légère, pli simple, ourlet à reprendre si besoin. Doublure courte à l'avant.",
    price: 172,
    category: "pantalons",
    collection: "essentiels",
    images: [
      frame("product-pantalon-noir"),
      frame("product-pantalon-noir-2"),
    ],
    sizes: apparelSizes,
    colors: [{ name: "Noir", hex: "#141311" }],
    stock: 12,
    featured: false,
    isNew: false,
    bestseller: false,
    createdAt: "2026-03-11",
  },
  {
    id: "complet-marine",
    name: "Complet Marine",
    slug: "complet-marine",
    description: "Veste déstructurée et pantalon assorti. Une allure complète, sans l'armature d'un costume de cérémonie.",
    details: "Toile marine, épaule douce, deux boutons, poche poitrine. Le bordeaux de la cravate fait écho à la griffe, il n'est pas imposé.",
    price: 460,
    compareAtPrice: 520,
    category: "complets",
    collection: "signature",
    images: [
      frame("product-complet-marine"),
      frame("product-complet-marine-2"),
    ],
    sizes: apparelSizes,
    colors: [{ name: "Marine", hex: "#1d2a44" }],
    stock: 6,
    featured: true,
    isNew: true,
    bestseller: false,
    createdAt: "2026-09-15",
  },
  {
    id: "complet-nuit",
    name: "Complet Nuit",
    slug: "complet-nuit",
    description: "Le noir entier. Veste qui marche, pantalon qui suit, rien qui brille trop.",
    details: "Coupe proche du corps sans serrer, revers moyen, intérieur non contrasté. Pour le soir et pour le jour.",
    price: 440,
    category: "complets",
    collection: "nouvelle-saison",
    images: [
      frame("product-complet-nuit"),
      frame("product-complet-nuit-2"),
    ],
    sizes: apparelSizes,
    colors: [{ name: "Noir", hex: "#12110f" }],
    stock: 7,
    featured: true,
    isNew: false,
    bestseller: false,
    createdAt: "2026-07-04",
  },
  {
    id: "ceinture-cuir",
    name: "Ceinture Cuir",
    slug: "ceinture-cuir",
    description: "Une lanière fine, boucle discrète. Elle tient le pantalon sans devenir un bijou.",
    details: "Cuir pleine fleur, largeur 3 cm, boucle mate. Planche d'atelier en attendant la photo produit.",
    price: 95,
    category: "accessoires",
    collection: "essentiels",
    images: [
      frame("product-ceinture"),
      frame("product-ceinture-2"),
    ],
    sizes: ["85", "90", "95", "100"],
    colors: [{ name: "Noir", hex: "#1a1816" }],
    stock: 20,
    featured: false,
    isNew: false,
    bestseller: false,
    createdAt: "2026-02-02",
  },
  {
    id: "pochette",
    name: "Pochette",
    slug: "pochette",
    description: "Un carré de poche, bordeaux profond. La seule note de couleur quand le complet reste sombre.",
    details: "Tissu souple, ourlet roulé, se plie en pointe ou à plat. La teinte reprend le wordmark.",
    price: 48,
    category: "accessoires",
    collection: "signature",
    images: [
      frame("product-pochette"),
      frame("product-pochette-2"),
    ],
    sizes: ["Unique"],
    colors: [{ name: "Bordeaux", hex: "#6b2e3c" }],
    stock: 22,
    featured: false,
    isNew: true,
    bestseller: false,
    createdAt: "2026-09-18",
  },
]

export function relatedTo(product: Product, all: Product[]) {
  return all
    .filter((item) => item.id !== product.id && (item.category === product.category || item.collection === product.collection))
    .slice(0, 4)
}

export const sizeGuide = [
  { size: "S", chest: "92", waist: "76", hip: "94" },
  { size: "M", chest: "96", waist: "81", hip: "98" },
  { size: "L", chest: "102", waist: "86", hip: "104" },
  { size: "XL", chest: "108", waist: "92", hip: "110" },
]
