/**
 * Registre unique des médias Moluki Alembakate.
 * origin "maison" : photographie réelle de la maison.
 * origin "reference" : visuel libre, sans logo tiers, en attendant le shooting.
 * origin "attente" : aucun fichier. Déposer l'image sur src, puis retirer placeholder.
 */
export type MediaFolder = "hero" | "campaign" | "lookbook" | "products" | "details" | "categories" | "brand" | "social"

export type MediaOrigin = "maison" | "reference" | "attente"

export type MediaRatio = "16:9" | "4:5" | "3:4" | "1:1" | "2:3"

export type MediaAsset = {
  id: string
  src?: string
  alt: string
  category: MediaFolder
  title: string
  position: string
  product?: string
  origin: MediaOrigin
  placeholder?: boolean
  ratio: MediaRatio
  /** Cadre serré sur le wordmark, pour la photo maison qui contient d'autres éléments. */
  crop?: boolean
}

const house = "42% 56%"

function asset(entry: MediaAsset): MediaAsset {
  return entry
}

export const mediaLibrary = [
  asset({
    id: "hero-campagne",
    src: "/media/hero/campagne.jpg",
    alt: "Tee-shirt ivoire Moluki Alembakate porté, wordmark bordeaux",
    category: "hero",
    title: "Campagne",
    position: house,
    product: "tee-shirt-griffe",
    origin: "maison",
    ratio: "3:4",
    crop: true,
  }),
  asset({
    id: "brand-wordmark",
    src: "/media/brand/wordmark.jpg",
    alt: "Wordmark bordeaux Moluki Alembakate sur le jersey ivoire",
    category: "brand",
    title: "Wordmark",
    position: house,
    product: "tee-shirt-griffe",
    origin: "maison",
    ratio: "4:5",
    crop: true,
  }),
  asset({
    id: "brand-silhouette",
    src: "/media/brand/silhouette.jpg",
    alt: "Silhouette Moluki Alembakate, tee-shirt ivoire",
    category: "brand",
    title: "Silhouette",
    position: house,
    product: "tee-shirt-griffe",
    origin: "maison",
    ratio: "2:3",
    crop: true,
  }),
  asset({
    id: "campaign-ligne",
    src: "/media/campaign/ligne.jpg",
    alt: "Complet marine et chemise claire, visuel de référence",
    category: "campaign",
    title: "La ligne",
    position: "center 18%",
    origin: "reference",
    ratio: "16:9",
  }),
  asset({
    id: "campaign-chemise",
    src: "/media/campaign/chemise.jpg",
    alt: "Chemise blanche, visuel de référence",
    category: "campaign",
    title: "Chemise",
    position: "center 28%",
    origin: "reference",
    ratio: "4:5",
  }),
  asset({
    id: "campaign-marche",
    src: "/media/campaign/marche.jpg",
    alt: "Silhouette noire en marche, visuel de référence",
    category: "campaign",
    title: "Marche",
    position: "center 22%",
    origin: "reference",
    ratio: "2:3",
  }),
  asset({
    id: "campaign-sable",
    src: "/media/campaign/sable.jpg",
    alt: "Couche claire et pantalon sable, visuel de référence",
    category: "campaign",
    title: "Sable",
    position: "center 32%",
    origin: "reference",
    ratio: "3:4",
  }),
  asset({
    id: "campaign-jersey",
    src: "/media/campaign/jersey.jpg",
    alt: "Jersey col rond, visuel de référence",
    category: "campaign",
    title: "Jersey",
    position: "center 40%",
    origin: "reference",
    ratio: "1:1",
  }),
  asset({
    id: "campaign-bordeaux",
    src: "/media/campaign/bordeaux.jpg",
    alt: "Veste sombre et note bordeaux, visuel de référence",
    category: "campaign",
    title: "Bordeaux",
    position: "center 20%",
    origin: "reference",
    ratio: "3:4",
  }),
  asset({
    id: "look-moluki",
    src: "/media/lookbook/01-moluki.jpg",
    alt: "Look Moluki, tee-shirt griffe porté",
    category: "lookbook",
    title: "Moluki",
    position: house,
    product: "tee-shirt-griffe",
    origin: "maison",
    ratio: "2:3",
    crop: true,
  }),
  asset({
    id: "look-alembakate",
    src: "/media/lookbook/02-alembakate.jpg",
    alt: "Look Alembakate, couche claire, visuel de référence",
    category: "lookbook",
    title: "Alembakate",
    position: "center 32%",
    product: "pantalon-ivoire",
    origin: "reference",
    ratio: "2:3",
  }),
  asset({
    id: "look-signature",
    src: "/media/lookbook/03-signature.jpg",
    alt: "Look Signature, complet sombre, visuel de référence",
    category: "lookbook",
    title: "Signature",
    position: "center 18%",
    product: "complet-marine",
    origin: "reference",
    ratio: "3:4",
  }),
  asset({
    id: "detail-griffe",
    src: "/media/details/griffe.jpg",
    alt: "Wordmark Moluki Alembakate sur le jersey",
    category: "details",
    title: "La griffe",
    position: house,
    product: "tee-shirt-griffe",
    origin: "maison",
    ratio: "4:5",
    crop: true,
  }),
  asset({ id: "detail-col", alt: "Col", category: "details", title: "Le col", position: "center", origin: "attente", placeholder: true, ratio: "1:1" }),
  asset({ id: "detail-couture", alt: "Couture", category: "details", title: "La couture", position: "center", origin: "attente", placeholder: true, ratio: "1:1" }),
  asset({ id: "detail-bouton", alt: "Bouton", category: "details", title: "Le bouton", position: "center", origin: "attente", placeholder: true, ratio: "1:1" }),
  asset({ id: "detail-tissu", alt: "Tissu", category: "details", title: "Le tissu", position: "center", origin: "attente", placeholder: true, ratio: "4:5" }),
  asset({ id: "detail-finition", alt: "Finition", category: "details", title: "La finition", position: "center", origin: "attente", placeholder: true, ratio: "3:4" }),
  asset({ id: "detail-etiquette", alt: "Étiquette", category: "details", title: "L'étiquette", position: "center", origin: "attente", placeholder: true, ratio: "1:1" }),
  asset({
    id: "category-chemises",
    src: "/media/categories/chemises.jpg",
    alt: "Chemise blanche, visuel de référence",
    category: "categories",
    title: "Chemises",
    position: "center 30%",
    origin: "reference",
    ratio: "3:4",
  }),
  asset({
    id: "category-polos",
    src: "/media/categories/polos.svg",
    alt: "Planche atelier du polo",
    category: "categories",
    title: "Polos",
    position: "center",
    origin: "reference",
    ratio: "3:4",
  }),
  asset({
    id: "category-complets",
    src: "/media/categories/complets.jpg",
    alt: "Complet sombre, visuel de référence",
    category: "categories",
    title: "Complets",
    position: "center 20%",
    origin: "reference",
    ratio: "3:4",
  }),
  asset({
    id: "category-tshirts",
    src: "/media/categories/t-shirts.jpg",
    alt: "Tee-shirt griffe Moluki Alembakate",
    category: "categories",
    title: "T-shirts",
    position: house,
    product: "tee-shirt-griffe",
    origin: "maison",
    ratio: "3:4",
    crop: true,
  }),
  asset({
    id: "category-pantalons",
    src: "/media/categories/pantalons.jpg",
    alt: "Pantalon clair, visuel de référence",
    category: "categories",
    title: "Pantalons",
    position: "center 70%",
    origin: "reference",
    ratio: "3:4",
  }),
  asset({
    id: "category-accessoires",
    src: "/media/categories/accessoires.svg",
    alt: "Planche atelier d'un accessoire",
    category: "categories",
    title: "Accessoires",
    position: "center",
    origin: "reference",
    ratio: "3:4",
  }),
  asset({
    id: "product-tee-griffe",
    src: "/media/products/tee-griffe.jpg",
    alt: "Tee-shirt ivoire Moluki Alembakate porté, wordmark bordeaux",
    category: "products",
    title: "Tee-shirt Griffe",
    position: house,
    product: "tee-shirt-griffe",
    origin: "maison",
    ratio: "3:4",
    crop: true,
  }),
  asset({
    id: "product-tee-coton",
    src: "/media/products/tee-coton.jpg",
    alt: "Jersey col rond, visuel de référence",
    category: "products",
    title: "Tee-shirt Coton",
    position: "center 40%",
    product: "tee-shirt-coton",
    origin: "reference",
    ratio: "3:4",
  }),
  asset({
    id: "product-chemise-atelier",
    src: "/media/products/chemise-atelier.jpg",
    alt: "Chemise blanche col classique, visuel de référence",
    category: "products",
    title: "Chemise Atelier",
    position: "center 30%",
    product: "chemise-atelier",
    origin: "reference",
    ratio: "3:4",
  }),
  asset({
    id: "product-chemise-atelier-2",
    src: "/media/products/chemise-atelier-2.jpg",
    alt: "Chemise blanche sous une veste sombre, visuel de référence",
    category: "products",
    title: "Chemise Atelier, seconde vue",
    position: "center 28%",
    product: "chemise-atelier",
    origin: "reference",
    ratio: "4:5",
  }),
  asset({
    id: "product-chemise-nuit",
    src: "/media/products/chemise-nuit.jpg",
    alt: "Chemise noire, visuel de référence",
    category: "products",
    title: "Chemise Nuit",
    position: "center 25%",
    product: "chemise-nuit",
    origin: "reference",
    ratio: "3:4",
  }),
  asset({
    id: "product-chemise-nuit-2",
    src: "/media/products/chemise-nuit-2.jpg",
    alt: "Silhouette noire, visuel de référence",
    category: "products",
    title: "Chemise Nuit, seconde vue",
    position: "center 20%",
    product: "chemise-nuit",
    origin: "reference",
    ratio: "2:3",
  }),
  asset({
    id: "product-polo-ivoire",
    src: "/media/products/polo-ivoire.svg",
    alt: "Planche atelier du polo ivoire",
    category: "products",
    title: "Polo Ivoire",
    position: "center",
    product: "polo-ivoire",
    origin: "reference",
    ratio: "1:1",
  }),
  asset({
    id: "product-polo-noir",
    src: "/media/products/polo-noir.svg",
    alt: "Planche atelier du polo noir",
    category: "products",
    title: "Polo Noir",
    position: "center",
    product: "polo-noir",
    origin: "reference",
    ratio: "1:1",
  }),
  asset({
    id: "product-pantalon-ivoire",
    src: "/media/products/pantalon-ivoire.jpg",
    alt: "Pantalon ivoire porté avec le tee-shirt griffe",
    category: "products",
    title: "Pantalon Ivoire",
    position: "center 78%",
    product: "pantalon-ivoire",
    origin: "maison",
    ratio: "2:3",
  }),
  asset({
    id: "product-pantalon-ivoire-2",
    src: "/media/products/pantalon-ivoire-2.jpg",
    alt: "Pantalon clair, visuel de référence",
    category: "products",
    title: "Pantalon Ivoire, seconde vue",
    position: "center 72%",
    product: "pantalon-ivoire",
    origin: "reference",
    ratio: "3:4",
  }),
  asset({
    id: "product-pantalon-noir",
    src: "/media/products/pantalon-noir.jpg",
    alt: "Pantalon noir, visuel de référence",
    category: "products",
    title: "Pantalon Noir",
    position: "center 70%",
    product: "pantalon-noir",
    origin: "reference",
    ratio: "2:3",
  }),
  asset({
    id: "product-pantalon-noir-2",
    src: "/media/products/pantalon-noir-2.jpg",
    alt: "Taille et veste noire, visuel de référence",
    category: "products",
    title: "Pantalon Noir, seconde vue",
    position: "center 75%",
    product: "pantalon-noir",
    origin: "reference",
    ratio: "4:5",
  }),
  asset({
    id: "product-complet-marine",
    src: "/media/products/complet-marine.jpg",
    alt: "Complet marine, visuel de référence",
    category: "products",
    title: "Complet Marine",
    position: "center 18%",
    product: "complet-marine",
    origin: "reference",
    ratio: "3:4",
  }),
  asset({
    id: "product-complet-marine-2",
    src: "/media/products/complet-marine-2.jpg",
    alt: "Veste sombre et note bordeaux, visuel de référence",
    category: "products",
    title: "Complet Marine, seconde vue",
    position: "center 22%",
    product: "complet-marine",
    origin: "reference",
    ratio: "4:5",
  }),
  asset({
    id: "product-complet-nuit",
    src: "/media/products/complet-nuit.jpg",
    alt: "Complet noir en marche, visuel de référence",
    category: "products",
    title: "Complet Nuit",
    position: "center 20%",
    product: "complet-nuit",
    origin: "reference",
    ratio: "2:3",
  }),
  asset({
    id: "product-complet-nuit-2",
    src: "/media/products/complet-nuit-2.jpg",
    alt: "Détail du complet noir, visuel de référence",
    category: "products",
    title: "Complet Nuit, seconde vue",
    position: "center 30%",
    product: "complet-nuit",
    origin: "reference",
    ratio: "4:5",
  }),
  asset({
    id: "product-ceinture",
    src: "/media/products/ceinture.svg",
    alt: "Planche atelier de la ceinture",
    category: "products",
    title: "Ceinture",
    position: "center",
    product: "ceinture-cuir",
    origin: "reference",
    ratio: "1:1",
  }),
  asset({
    id: "product-ceinture-2",
    src: "/media/products/ceinture-2.jpg",
    alt: "Taille habillée, visuel de référence",
    category: "products",
    title: "Ceinture, seconde vue",
    position: "center 80%",
    product: "ceinture-cuir",
    origin: "reference",
    ratio: "4:5",
  }),
  asset({
    id: "product-pochette",
    src: "/media/products/pochette.svg",
    alt: "Planche atelier de la pochette",
    category: "products",
    title: "Pochette",
    position: "center",
    product: "pochette",
    origin: "reference",
    ratio: "1:1",
  }),
  asset({
    id: "product-pochette-2",
    src: "/media/products/pochette-2.jpg",
    alt: "Poche de veste, visuel de référence",
    category: "products",
    title: "Pochette, seconde vue",
    position: "62% 32%",
    product: "pochette",
    origin: "reference",
    ratio: "1:1",
  }),
  asset({
    id: "social-01",
    src: "/media/social/01.jpg",
    alt: "Wordmark Moluki Alembakate porté",
    category: "social",
    title: "Griffe",
    position: house,
    product: "tee-shirt-griffe",
    origin: "maison",
    ratio: "3:4",
    crop: true,
  }),
  asset({
    id: "social-02",
    src: "/media/social/02.jpg",
    alt: "Allure claire, visuel de référence",
    category: "social",
    title: "Sable",
    position: "center 32%",
    origin: "reference",
    ratio: "3:4",
  }),
  asset({
    id: "social-03",
    src: "/media/social/03.jpg",
    alt: "Chemise blanche, visuel de référence",
    category: "social",
    title: "Chemise",
    position: "center 28%",
    origin: "reference",
    ratio: "4:5",
  }),
  asset({
    id: "social-04",
    src: "/media/social/04.jpg",
    alt: "Veste sombre, visuel de référence",
    category: "social",
    title: "Veste",
    position: "center 20%",
    origin: "reference",
    ratio: "1:1",
  }),
  asset({
    id: "social-05",
    src: "/media/social/05.jpg",
    alt: "Jersey, visuel de référence",
    category: "social",
    title: "Jersey",
    position: "center 40%",
    origin: "reference",
    ratio: "1:1",
  }),
  asset({
    id: "social-06",
    src: "/media/social/06.jpg",
    alt: "Complet, visuel de référence",
    category: "social",
    title: "Ligne",
    position: "center 18%",
    origin: "reference",
    ratio: "16:9",
  }),
  asset({
    id: "social-07",
    src: "/media/social/07.jpg",
    alt: "Silhouette noire, visuel de référence",
    category: "social",
    title: "Marche",
    position: "center 22%",
    origin: "reference",
    ratio: "2:3",
  }),
  asset({
    id: "social-08",
    src: "/media/social/08.jpg",
    alt: "Détail du wordmark Moluki Alembakate",
    category: "social",
    title: "Nom",
    position: house,
    product: "tee-shirt-griffe",
    origin: "maison",
    ratio: "4:5",
    crop: true,
  }),
  asset({
    id: "social-09",
    src: "/media/social/09.jpg",
    alt: "Pantalon clair, visuel de référence",
    category: "social",
    title: "Clair",
    position: "center 32%",
    origin: "reference",
    ratio: "2:3",
  }),
] as const satisfies readonly MediaAsset[]

const byId = new Map<string, MediaAsset>(mediaLibrary.map((item) => [item.id, item]))

export function getMedia(id: string): MediaAsset {
  const item = byId.get(id)
  if (!item) throw new Error(`Média inconnu : ${id}`)
  return item
}

export function mediaByCategory(category: MediaFolder): MediaAsset[] {
  return mediaLibrary.filter((item) => item.category === category)
}

export function frame(id: string): { src: string; alt: string; position: string } {
  const item = getMedia(id)
  if (!item.src) throw new Error(`Média sans fichier : ${id}`)
  return { src: item.src, alt: item.alt, position: item.position }
}

export function srcOf(id: string) {
  return frame(id).src
}

export const ratios: Record<MediaRatio, string> = {
  "16:9": "aspect-video",
  "4:5": "aspect-[4/5]",
  "3:4": "aspect-[3/4]",
  "1:1": "aspect-square",
  "2:3": "aspect-[2/3]",
}

export const imageSizes = {
  full: "100vw",
  wide: "(min-width: 768px) 70vw, 100vw",
  half: "(min-width: 768px) 50vw, 100vw",
  third: "(min-width: 1024px) 33vw, 50vw",
} as const
